# Generated by Django 3.2.9 on 2021-12-10 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auctionlistings',
            name='current_price',
            field=models.FloatField(max_length=7),
        ),
        migrations.AlterField(
            model_name='auctionlistings',
            name='starting_price',
            field=models.FloatField(max_length=7),
        ),
        migrations.AlterField(
            model_name='bids',
            name='bid_price',
            field=models.FloatField(max_length=7),
        ),
    ]
