# Generated by Django 3.2.9 on 2021-12-07 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_auctionlistings_bids_comments'),
    ]

    operations = [
        migrations.RenameField(
            model_name='auctionlistings',
            old_name='name',
            new_name='title',
        ),
        migrations.AddField(
            model_name='auctionlistings',
            name='category',
            field=models.CharField(default='', max_length=65),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='auctionlistings',
            name='current_price',
            field=models.CharField(default='', max_length=7),
            preserve_default=False,
        ),
    ]
