# Generated by Django 3.2.9 on 2021-12-10 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_auto_20211210_1055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auctionlistings',
            name='current_price',
            field=models.DecimalField(decimal_places=2, max_digits=7),
        ),
        migrations.AlterField(
            model_name='auctionlistings',
            name='starting_price',
            field=models.DecimalField(decimal_places=2, max_digits=7),
        ),
        migrations.AlterField(
            model_name='bids',
            name='bid_price',
            field=models.DecimalField(decimal_places=2, max_digits=7),
        ),
    ]
